export const TICKER_LIST = [
  'BTC',
  'ETH',
  'REP',
  'TRX',
  'APT',
  'GAS',
  'STRK',
  'XRP',
  'KAVA',
  'SAND',
  'MATIC',
  'ELF',
  'TON',
  'DOGE',
  'T',
  'SBD',
  'MTL',
  'QTUM',
  'HBAR',
  'NEO',
  'WAVES',
  'VET',
  'ETC',
  'AXS',
  'ANKR',
  'SHIB',
  'SOL',
  'MANA',
  'GMT',
  'ONG',
  'SXP',
  'SRM',
  'STRAX',
  'LSK',
  'AHT',
  'SC',
  'CRE',
  'NEAR',
  'AQT',
  'CHZ',
  'LINK',
  'PLA',
  'ATOM',
  'GRS',
  'ADA',
  'FLOW',
  'ZIL',
  'BTG',
  'EOS',
  'NU',
  'IQ',
  'STORJ',
  'WAXP',
  'RFR',
  'KNC',
  'GLM',
  'TFUEL',
  'POLYX',
  'ARK',
  'ARDR',
  'FCT2',
  'BORA',
  'ALGO',
  'AVAX',
  'HIFI',
  'CELO',
  'BSV',
  'MVL',
  'ORBS',
  'STMX',
  'HIVE',
  'PUNDIX',
  'XEC',
  'META',
  'STEEM',
  'DAWN',
  'POWR',
  'DKA',
  'STX',
  'AERGO',
  'CRO',
  'BAT',
  'CBK',
  'ONT',
  'STPT',
  'LOOM',
  'JST',
  'CVC',
  '1INCH',
  'BCH',
  'ENJ',
  'HUM',
  'MBL',
  'OMG',
  'DOT',
  'AAVE',
  'ICX',
  'XLM',
  'QKC',
  'IOST',
  'UPP',
  'TT',
  'ZRX',
  'MED',
  'HUNT',
  'MOC',
  'XEM',
  'MILK',
  'XTZ',
  'SSX',
  'SNT',
  'IOTA',
  'THETA',
  'BTT',
];

export const TICKER_MAP = new Map([
  ['BTC', '비트코인'],
  ['ETH', '이더리움'],
  ['REP', '어거'],
  ['TRX', '트론'],
  ['APT', '앱토스'],
  ['GAS', '가스'],
  ['STRK', '스트라이크'],
  ['XRP', '리플'],
  ['KAVA', '카바'],
  ['SAND', '샌드박스'],
  ['MATIC', '폴리곤'],
  ['ELF', '엘프'],
  ['TON', '톤'],
  ['DOGE', '도지코인'],
  ['T', '쓰레스홀드'],
  ['SBD', '스팀달러'],
  ['MTL', '메탈'],
  ['QTUM', '퀀텀'],
  ['HBAR', '헤데라'],
  ['NEO', '네오'],
  ['WAVES', '웨이브'],
  ['VET', '비체인'],
  ['ETC', '이더리움클래식'],
  ['AXS', '엑시인피니티'],
  ['ANKR', '앵커'],
  ['SHIB', '시바이누'],
  ['SOL', '솔라나'],
  ['MANA', '디센트럴랜드'],
  ['GMT', '스테픈'],
  ['ONG', '온톨로지가스'],
  ['SXP', '솔라'],
  ['SRM', '세럼'],
  ['STRAX', '스트라티스'],
  ['LSK', '리스크'],
  ['AHT', '아하토큰'],
  ['SC', '시아코인'],
  ['CRE', '캐리프로토콜'],
  ['NEAR', '니어프로토콜'],
  ['AQT', '알파쿼크'],
  ['CHZ', '칠리즈'],
  ['LINK', '체인링크'],
  ['PLA', '플레이댑'],
  ['ATOM', '코스모스'],
  ['GRS', '그로스톨코인'],
  ['ADA', '에이다'],
  ['FLOW', '플로우'],
  ['ZIL', '질리카'],
  ['BTG', '비트코인골드'],
  ['EOS', '이오스'],
  ['NU', '누사이퍼'],
  ['IQ', '아이큐'],
  ['STORJ', '스토리지'],
  ['WAXP', '왁스'],
  ['RFR', '리퍼리움'],
  ['KNC', '카이버네트워크'],
  ['GLM', '골렘'],
  ['TFUEL', '쎄타퓨엘'],
  ['POLYX', '폴리매쉬'],
  ['ARK', '아크'],
  ['ARDR', '아더'],
  ['FCT2', '피르마체인'],
  ['BORA', '보라'],
  ['ALGO', '알고랜드'],
  ['AVAX', '아발란체'],
  ['HIFI', '하이파이'],
  ['CELO', '셀로'],
  ['BSV', '비트코인에스브이'],
  ['MVL', '엠블'],
  ['ORBS', '오브스'],
  ['STMX', '스톰엑스'],
  ['HIVE', '하이브'],
  ['PUNDIX', '펀디엑스'],
  ['XEC', '이캐시'],
  ['META', '메타디움'],
  ['STEEM', '스팀'],
  ['DAWN', '던프로토콜'],
  ['POWR', '파워렛저'],
  ['DKA', '디카르고'],
  ['STX', '스택스'],
  ['AERGO', '아르고'],
  ['CRO', '크로노스'],
  ['BAT', '베이직어텐션토큰'],
  ['CBK', '코박토큰'],
  ['ONT', '온톨로지'],
  ['STPT', '에스티피'],
  ['LOOM', '룸네트워크'],
  ['JST', '저스트'],
  ['CVC', '시빅'],
  ['1INCH', '1인치네트워크'],
  ['BCH', '비트코인캐시'],
  ['ENJ', '엔진코인'],
  ['HUM', '휴먼스케이프'],
  ['MBL', '무비블록'],
  ['OMG', '오미세고'],
  ['DOT', '폴카닷'],
  ['AAVE', '에이브'],
  ['ICX', '아이콘'],
  ['XLM', '스텔라루멘'],
  ['QKC', '쿼크체인'],
  ['IOST', '아이오에스티'],
  ['UPP', '센티넬프로토콜'],
  ['TT', '썬더코어'],
  ['ZRX', '제로엑스'],
  ['MED', '메디블록'],
  ['HUNT', '헌트'],
  ['MOC', '모스코인'],
  ['XEM', '넴'],
  ['MILK', '밀크'],
  ['XTZ', '테조스'],
  ['SSX', '썸씽'],
  ['SNT', '스테이터스네트워크토큰'],
  ['IOTA', '아이오타'],
  ['THETA', '쎄타토큰'],
  ['BTT', '비트토렌트'],
]);
